import BlogArticle from './BlogArticle';
import styles from './page.module.css';

export const metadata = {
  title: 'Blog',
  description: 'Blog page.',
};

export const article =
  'This is a fake article generated by AI. Recently, I decided to combine my love for retro gaming with my interest in microcontrollers and build a mini arcade machine. I used a Raspberry Pi Pico as the heart of the project, pairing it with a small LCD screen and a few arcade buttons for that classic feel. The setup was fairly simple. I loaded retro arcade game emulators onto the Pico and connected it to the LCD. Then, I wired up the buttons and joystick, using the GPIO pins on the microcontroller to read inputs. With a bit of programming, I was able to map the controls to mimic classic arcade machines. Once I had everything connected, I 3D-printed a small arcade-style case to house the setup. Now, I have my very own mini arcade cabinet that plays games like Pac-Man and Space Invaders, all powered by a microcontroller! It is a nostalgic and fun project, perfect for any retro game lover.';

export default function BlogPage() {
  return (
    <div className={styles.page}>
      <h1>Blog</h1>
      <BlogArticle
        author="Sandy Storyteller"
        date={new Date('10-14-2024')}
        title="Building My Own Mini Arcade Machine with a Microcontroller"
        article={article}
      />
      <BlogArticle
        author="Peter Poet"
        date={new Date('10-05-2024')}
        title="Building My Own Mini Arcade Machine with a Microcontroller"
        article={article}
      />
      <BlogArticle
        author="Ben Binder"
        date={new Date('09-10-2024')}
        title="Building My Own Mini Arcade Machine with a Microcontroller"
        article={article}
      />
      <BlogArticle
        author="Clara Composition"
        date={new Date('08-22-2024')}
        title="Building My Own Mini Arcade Machine with a Microcontroller"
        article={article}
      />
      <BlogArticle
        author="Wendy Wordsmith"
        date={new Date('07-01-2024')}
        title="Building My Own Mini Arcade Machine with a Microcontroller"
        article={article}
      />
    </div>
  );
}
