import { Sql } from 'postgres';

const products = [
  { id: 1, name: 'Arduino Mega 2560 Rev3', price: 3822 },
  { id: 2, name: 'Arduino Nano 33 IoT', price: 2672 },
  { id: 3, name: 'Arduino Uno R4 WiFi', price: 2461 },
  { id: 4, name: 'Arduino Uno Rev3', price: 2037 },
  { id: 5, name: 'Bluefruit LE Usb Sniffer nRF51822-v2', price: 2790 },
  { id: 6, name: 'Nordic Semiconductor nRF52840', price: 1690 },
  { id: 7, name: 'Sparkfun Thing Plus ESP32 WROOM', price: 2380 },
  { id: 8, name: 'Raspberry Pi Pico WH RP2040', price: 726 },
  { id: 9, name: 'Waveshare ESP32 C6 WROOM-1-N8', price: 958 },
  { id: 10, name: 'Waveshare ESP32 S3 Nano', price: 998 },
];

const fakeDescription =
  'This is a fake description generated by AI. Unlock the power of innovation with our QuantumChip Microcontroller Series. Designed for hobbyists, engineers, and makers alike, these advanced microcontrollers offer unparalleled performance and versatility for all your projects. Whether you are building a robotic arm, creating smart home devices, or diving into IoT applications, QuantumChip is your ultimate companion. \\nEach QuantumChip microcontroller is powered by a cutting-edge 32-bit architecture, delivering lightning-fast processing speeds and enhanced efficiency. With up to 256KB of flash memory and 64KB of SRAM, you will have all the storage you need to run complex algorithms and manage multiple tasks seamlessly. \\nWhat sets the QuantumChip apart is its built-in Wi-Fi and Bluetooth connectivity, allowing you to create connected devices with ease. Our intuitive programming environment supports popular languages like C++, Python, and JavaScript, ensuring you can get started quickly, regardless of your skill level. Plus, with an extensive library of pre-built functions and sample projects, you will have everything you need right at your fingertips. \\nThe QuantumChip Microcontroller Series is designed with durability in mind. Its compact form factor and low power consumption make it perfect for portable applications, while robust safety features protect your projects from power surges and overheating. \\nJoin the community of innovators who trust QuantumChip. Whether you are a seasoned developer or just getting started, our microcontrollers are engineered to empower your creativity. Embrace the future of technology and bring your ideas to life with QuantumChip, where every project is a possibility.';

export async function up(sql: Sql) {
  for (const product of products) {
    await sql`
      INSERT INTO
        products (name, price, description)
      VALUES
        (
          ${product.name},
          ${product.price},
          ${fakeDescription}
        )
    `;
  }
}

export async function down(sql: Sql) {
  for (const product of products) {
    await sql`
      DELETE FROM products
      WHERE
        id = ${product.id}
    `;
  }
}
