import { Sql } from 'postgres';
import { productType } from '../app/util/constants';

const fakeDescriptionMicrocontroller =
  'This is a fake description generated by AI. Unlock the power of innovation with our QuantumChip Microcontroller Series. Designed for hobbyists, engineers, and makers alike, these advanced microcontrollers offer unparalleled performance and versatility for all your projects. Whether you are building a robotic arm, creating smart home devices, or diving into IoT applications, QuantumChip is your ultimate companion. \\nEach QuantumChip microcontroller is powered by a cutting-edge 32-bit architecture, delivering lightning-fast processing speeds and enhanced efficiency. With up to 256KB of flash memory and 64KB of SRAM, you will have all the storage you need to run complex algorithms and manage multiple tasks seamlessly. \\nWhat sets the QuantumChip apart is its built-in Wi-Fi and Bluetooth connectivity, allowing you to create connected devices with ease. Our intuitive programming environment supports popular languages like C++, Python, and JavaScript, ensuring you can get started quickly, regardless of your skill level. Plus, with an extensive library of pre-built functions and sample projects, you will have everything you need right at your fingertips. \\nThe QuantumChip Microcontroller Series is designed with durability in mind. Its compact form factor and low power consumption make it perfect for portable applications, while robust safety features protect your projects from power surges and overheating. \\nJoin the community of innovators who trust QuantumChip. Whether you are a seasoned developer or just getting started, our microcontrollers are engineered to empower your creativity. Embrace the future of technology and bring your ideas to life with QuantumChip, where every project is a possibility.';

const fakeDescriptionJoystick =
  'This is a fake description generated by AI. Unleash your gaming potential with the UltraGrip X2000, the ultimate joystick designed for serious gamers and casual players alike! Featuring a cutting-edge ergonomic design, the X2000 fits comfortably in your hand, reducing fatigue during marathon gaming sessions. With customizable buttons, an adjustable sensitivity range, and a responsive 360-degree joystick movement, you will dominate every virtual battlefield with precision. \\nThe X2000 comes equipped with RGB lighting that syncs with your gameplay for an immersive experience, plus built-in haptic feedback to feel every explosion and impact. Compatible with all major consoles and PCs, it is the versatile tool you need to elevate your gaming. Don not just play; play smart with the UltraGrip X2000!';

const fakeDescriptionButton =
  'This is a fake description generated by AI. Step into the world of arcade gaming with the Turbo Button Blast! This innovative push button elevates your gaming experience to exhilarating new heights. Designed for rapid-fire action, it features a high-response sensitivity that registers your every click with lightning speed. The ergonomic design ensures hours of comfortable gameplay, while customizable LED lights flash in sync with your in-game achievements. Compatible with all major arcade systems, Turbo Button Blast transforms any game into an epic showdown. Get ready to unleash your inner champion!';

const products = [
  {
    id: 1,
    name: 'Arduino Mega 2560 Rev3',
    type: productType.microcontroller,
    price: 3822,
    description: fakeDescriptionMicrocontroller,
  },
  {
    id: 2,
    name: 'Arduino Nano 33 IoT',
    type: productType.microcontroller,
    price: 2672,
    description: fakeDescriptionMicrocontroller,
  },
  {
    id: 3,
    name: 'Arduino Uno R4 WiFi',
    type: productType.microcontroller,
    price: 2461,
    description: fakeDescriptionMicrocontroller,
  },
  {
    id: 4,
    name: 'Arduino Uno Rev3',
    type: productType.microcontroller,
    price: 2037,
    description: fakeDescriptionMicrocontroller,
  },
  {
    id: 5,
    name: 'Bluefruit LE Usb Sniffer nRF51822-v2',
    type: productType.microcontroller,
    price: 2790,
    description: fakeDescriptionMicrocontroller,
  },
  {
    id: 6,
    name: 'Nordic Semiconductor nRF52840',
    type: productType.microcontroller,
    price: 1690,
    description: fakeDescriptionMicrocontroller,
  },
  {
    id: 7,
    name: 'Sparkfun Thing Plus ESP32 WROOM',
    type: productType.microcontroller,
    price: 2380,
    description: fakeDescriptionMicrocontroller,
  },
  {
    id: 8,
    name: 'Raspberry Pi Pico WH RP2040',
    type: productType.microcontroller,
    price: 726,
    description: fakeDescriptionMicrocontroller,
  },
  {
    id: 9,
    name: 'Waveshare ESP32 C6 WROOM-1-N8',
    type: productType.microcontroller,
    price: 958,
    description: fakeDescriptionMicrocontroller,
  },
  {
    id: 10,
    name: 'Waveshare ESP32 S3 Nano',
    type: productType.microcontroller,
    price: 998,
    description: fakeDescriptionMicrocontroller,
  },
  {
    id: 11,
    name: 'iL Eurojoystick Red',
    type: productType.joystick,
    price: 1567,
    description: fakeDescriptionJoystick,
  },
  {
    id: 12,
    name: 'Paradise Black Top',
    type: productType.joystick,
    price: 1012,
    description: fakeDescriptionJoystick,
  },
  {
    id: 13,
    name: 'Sanwa JLFD-TP-8YD',
    type: productType.joystick,
    price: 1567,
    description: fakeDescriptionJoystick,
  },
  {
    id: 14,
    name: 'Crown CWL-309FJ-DX',
    type: productType.joystick,
    price: 2769,
    description: fakeDescriptionJoystick,
  },
  {
    id: 15,
    name: 'Seimitsu LS-58',
    type: productType.joystick,
    price: 2030,
    description: fakeDescriptionJoystick,
  },
  {
    id: 16,
    name: 'Sanwa OBSF-30 Snap-in',
    type: productType.button,
    price: 254,
    description: fakeDescriptionButton,
  },
  {
    id: 17,
    name: 'iL PSL-L Concave',
    type: productType.button,
    price: 245,
    description: fakeDescriptionButton,
  },
  {
    id: 18,
    name: 'Crown SAMDUCKSA SDB-202M Cherry',
    type: productType.button,
    price: 550,
    description: fakeDescriptionButton,
  },
  {
    id: 19,
    name: 'OBS-MX Switch',
    type: productType.button,
    price: 231,
    description: fakeDescriptionButton,
  },
  {
    id: 20,
    name: 'Paradise LED Button',
    type: productType.button,
    price: 176,
    description: fakeDescriptionButton,
  },
];

export async function up(sql: Sql) {
  for (const product of products) {
    await sql`
      INSERT INTO
        products (
          name,
          type,
          price,
          description
        )
      VALUES
        (
          ${product.name},
          ${product.type},
          ${product.price},
          ${product.description}
        )
    `;
  }
}

export async function down(sql: Sql) {
  for (const product of products) {
    await sql`
      DELETE FROM products
      WHERE
        id = ${product.id}
    `;
  }
}
