import Image from 'next/image';
import Link from 'next/link';
import type { ProductDb } from '../../../../../database/products';
import { centsToEuros } from '../../../../util/parsers';
import AddToCartForm from './AddToCartForm';
import styles from './ProductCardBig.module.css';

type Props = {
  product: ProductDb;
};

export default function ProductCardBig({ product }: Props) {
  const descriptionParagraphs = product.description?.split('\\n');

  return (
    <div className={styles.cardBig}>
      <Link className={styles.return} href="/shop">
        <div className={styles.spin}>⇦</div>
        <div>return</div>
      </Link>
      <h1 className={styles.name}>{product.name}</h1>
      <h3 className="typewriter">Product Details:</h3>
      <div className={styles.eyecatcher}>
        <div className={styles.imgContainer}>
          <Image
            src={`/images/${product.imgName}`}
            alt={`Image of ${product.name}`}
            width={600}
            height={400}
            className={styles.img}
            data-test-id="product-image"
          />
        </div>
        <div className={styles.addToCart}>
          <table className={styles.table}>
            <tbody>
              <tr>
                <td>Product code:</td>
                <td>{product.id}</td>
              </tr>
              <tr>
                <td>Price:</td>
                <td className="euro" data-test-id="product-price">
                  {centsToEuros(product.price)}
                </td>
              </tr>
            </tbody>
          </table>
          <AddToCartForm productId={product.id} />
        </div>
      </div>

      {descriptionParagraphs && (
        <article className={styles.article}>
          <hr />
          <h3>Description:</h3>
          {descriptionParagraphs.map((paragraph) => {
            return (
              <p key={`paragraph-${paragraph.slice(1, 20)}`}>
                <br />
                {paragraph}
              </p>
            );
          })}
        </article>
      )}

      <article className={styles.article}>
        <hr />
        <h3>Specification:</h3>
        <br />
        <p>This is a fake specification generated by AI.</p>
        <br />
        <ul className={styles.specList}>
          <li>Minimum Voltage: 3.3V</li>
          <li>Maximum Voltage: 5V</li>
          <li>Minimum Current: 10mA</li>
          <li>Maximum Current: 500mA</li>
        </ul>
      </article>
    </div>
  );
}
