import Link from 'next/link';
import { productType } from '../util/constants';
import BlogArticle from './blog/BlogArticle';
import ShopNowCard from './components/ShopNowCard';
import styles from './page.module.css';

const article =
  'This is a fake article generated by AI. Recently, I decided to combine my love for retro gaming with my interest in microcontrollers and build a mini arcade machine. I used a Raspberry Pi Pico as the heart of the project, pairing it with a small LCD screen and a few arcade buttons for that classic feel. The setup was fairly simple. I loaded retro arcade game emulators onto the Pico and connected it to the LCD. Then, I wired up the buttons and joystick, using the GPIO pins on the microcontroller to read inputs. With a bit of programming, I was able to map the controls to mimic classic arcade machines. Once I had everything connected, I 3D-printed a small arcade-style case to house the setup. Now, I have my very own mini arcade cabinet that plays games like Pac-Man and Space Invaders, all powered by a microcontroller! It is a nostalgic and fun project, perfect for any retro game lover.';

export default function HomePage() {
  return (
    <div className={styles.page}>
      <h2>WELCOME TO</h2>
      <h1>Custom ARCADE</h1>
      <p className={styles.sloganPlatform}>
        Your trusted platform for building custom arcade machines.
      </p>
      <div className={styles.sloganContainer}>
        <h2 className={styles.sloganStart}>Learn.</h2>
        <h2 className={styles.sloganMiddle}>Create.</h2>
        <h2 className={styles.sloganEnd}>Enjoy!</h2>
      </div>
      <h2>GET PARTS</h2>
      <div className={styles.shopNow}>
        <ShopNowCard
          className={styles.shopNowStart}
          heading="Controllers"
          productType={productType.microcontroller}
        />
        <ShopNowCard
          className={styles.shopNowMiddle}
          heading="Buttons"
          productType={productType.button}
        />
        <ShopNowCard
          className={styles.shopNowEnd}
          heading="Joysticks"
          productType={productType.joystick}
        />
      </div>
      <div className={styles.blog}>
        <h2>Featured Blog Post</h2>
        <div className={styles.blogPost}>
          <BlogArticle
            author="Sandy Storyteller"
            date={new Date('10-14-2024')}
            title="Building My Own Mini Arcade Machine with a Microcontroller"
            articleText={article}
          />
        </div>
        <Link href="/blog">Read more.</Link>
      </div>
    </div>
  );
}
